### ISSUE TITLE
build production bug Modified the contents of the original document

### ISSUE THREAD

**Issue by hppking** [stylify/packages#155] opened 2022-12-06 09:08 UTC
const cssRecordSelector = config.mangledSelector ? this.mangledSelector : this.selector;
-> const cssRecordSelector = config.minimize ? this.mangledSelector : this.selector;

**Comment by Machy8** [comment] 2022-12-06 10:05
Hi, @hppking. 

Could you please provide a bit more detail on this issue? I don't understand, what you mean.

**Comment by hppking** [comment] 2022-12-07 02:27
@Machy8 
solidjs+stylify demo:
cmd yarn build production
![image](https://user-images.githubusercontent.com/16394419/206072723-919f6ed8-7813-490f-be54-86cf5f346515.png) to 
![image](https://user-images.githubusercontent.com/16394419/206072888-7a8fa99c-81c9-4b9d-9c77-977d1126960e.png)

**Comment by hppking** [comment] 2022-12-07 02:29
Cannot modify source file todo-list.jsx

**Comment by Machy8** [comment] 2022-12-07 06:49
This behavior is actually correct. Since some frameworks (Symfony, Laravel, Next) doesn't have hooks for generating files like NuxtJS does. Because of that, Stylify must access the files before framework compilers, therefore process source files directly.

However try to add `rewriteSelectorsInFiles: false` to your Bundle configuration as follows:
```js
 bundles: [
    {
      outputFile: './src/stylify.css',
      files: ['./src/**/*.jsx'],
      rewriteSelectorsInFiles: false,
    },
  ],
```
I have tested it in SolidJS example and it seems to work.

Then, you can run `yarn build` and the selectors will be rewritten only in build files.

**Comment by hppking** [comment] 2022-12-07 09:47
Good

**Comment by mzaini30** [comment] 2023-02-28 15:16
> This behavior is actually correct. Since some frameworks (Symfony, Laravel, Next) don't have hooks for generating files as NuxtJS does. Because of that, Stylify must access the files before framework compilers, therefore it processes source files directly.
> 
> However try to add `rewriteSelectorsInFiles: false` to your Bundle configuration as follows:
> 
> ```js
>  bundles: [
>     {
>       outputFile: './src/stylify.css',
>       files: ['./src/**/*.jsx'],
>       rewriteSelectorsInFiles: false,
>     },
>   ],
> ```
> 
> I have tested it in SolidJS example and it seems to work (I have updated the example).
> 
> Then, you can run `yarn build` and the selectors will be rewritten only in build files.

But not works in Svelte component parent

Dev:

```html
<div class="padding:10px background:pink">
  <p class="color:blue font-style:italic">Cat</p>
</div>
```

Build:

```html
<div class="padding:10px background:pink">
  <p class="c d">Cat</p>
</div>
```

**Comment by Machy8** [comment] 2023-02-28 17:35
Hi @mzaini30.

Are you using SvelteKit or svelte+vite or any other combination?

Could you please send the parent and child component? I will try to reproduce the error.

**Comment by mzaini30** [comment] 2023-02-28 21:11
I using it: https://github.com/mzaini30/svelte

**Comment by Machy8** [comment] 2023-02-28 21:40
I have forked your example. 

Here is your example with a working configuration: https://stackblitz.com/edit/github-z2waev?file=vite.config.js.

The problem is with Svelte compilation under the hood with the combination with Vite converts `class="..."` to `add_attribute(div, "class", "...")` that Stylify doesn't match. 

The only option here now is to remove the `rewriteSelectorsInFiles` option from the config. This will rewrite selectors during build (production) pipeline in Vercel/Github but not in local environment (unless you run build locally). 

If you need to test the production build process locally without selectors mangling or disabling it entirely, you can set the `mangleSelectors:false` in the Compiler config. I have added comment for you into the `vite.config.js` configuration at stackblitz: 

```js
const stylifyPlugin = stylifyVite({
	// ...
	bundles: [ /* */ ],
	compiler: {
		mangleSelectors: false
	}
});
```

![image](https://user-images.githubusercontent.com/14016808/221984390-65f376b2-4efa-46f1-aeb1-6f9d5831e705.png)

Please let me know if it works.

**Comment by mzaini30** [comment] 2023-02-28 21:53
I usually build it locally because I using compiled Svelte for Android app webview 😅

Okay, I'll use mangleSelectors false

**Comment by Machy8** [comment] 2023-02-28 22:04
Hm, this is bad. Sorry for that. 

I have tried to configure some parsing before you send me your repo, but Svelte compiles that into a ton of variants of output, so I haven't send any patch.

Will have to look into it. But I need to test it first.

You can possibly check if there is for example `.env.local` file in the `vite.config.js` through `fs.existsSync()`, which returns true/false and pass it to the compiler.

If the `.env.local` will be in the gitignore and not pushed into the git repository, it will always automatically setup dev environment. I do it for my repos in PHP frameworks like Symfony/Laravel and it works fine.

Something like:
```js
import fs from 'fs';

const isLocalEnv = fs.existsSync('./.env.local');

const stylifyPlugin = stylifyVite({
	// ...
	bundles: [ /* */ ],
	compiler: {
		mangleSelectors: !isLocalEnv
	}
});
```

**Comment by mzaini30** [comment] 2023-02-28 22:39
Nice idea. I'll create scripts like `pnpm build:online`

**Comment by Machy8** [comment] 2023-02-28 22:54
Try it. If you find any issues, let me know.

**Comment by mzaini30** [comment] 2023-02-28 22:55
Solved

```javascript
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import legacy from "@vitejs/plugin-legacy";
import pages from "vite-plugin-pages-svelte";
import { stylifyVite } from '@stylify/unplugin';

const stylifyPlugin = (mangle) => (stylifyVite({
    bundles: [{
        outputFile: './src/stylify.css',
        files: ['./src/**/*.svelte'],
    }],
    compiler: {
      mangleSelectors: mangle
    }
}));

let plugins = [
  svelte(),
  pages(),
];

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  if (mode == "android") {
    return {
      plugins: [legacy(), ...plugins, stylifyPlugin(false)],
    };
  } else if (mode == "online") {
    return {
      plugins: [...plugins, stylifyPlugin(true)],
    };
  } else {
    return {
      plugins: [...plugins, stylifyPlugin(false)],
    };
  }
});
```

**Comment by Machy8** [comment] 2023-02-28 23:20
Great! I will add this to snippets. Thanks a lot for testing!

**Comment by Machy8** [comment] 2023-05-17 06:06
The mangling is now opt-in.

**For further reading**.
Mangling info: https://stylifycss.com/en/docs/get-started/mangling-selectors/
Release info: https://stylifycss.com/en/docs/get-started/releases/

**Closed** 2023-05-17 06:07 UTC
