### ISSUE TITLE
I can't use Stylify on Astro

### ISSUE THREAD

**Issue by mzaini30** [stylify/packages#209] opened 2023-02-28 22:38 UTC
### Describe the bug

I can't use Stylify on my Astro minimal template. Why?

### Reproduction

https://github.com/mzaini30/astro-stylify

### Logs

```shell
Error: Cannot find module 'C:latihanastro-stylifysrcstylesstylify.css' imported from 'astro:scripts/page-ssr.js'
    at nodeImport (file:///C:/latihan/astro-stylify/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52451:25)
    at ssrImport (file:///C:/latihan/astro-stylify/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52374:20)
    at eval (astro:scripts/page-ssr.js:3:50)    at instantiateModule (file:///C:/latihan/astro-stylify/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52420:15)
```

### System Info

```shell
OS: Windows 11 (Phoenix Lite OS)

Text editor: VS Code

Terminal: Git Bash
```

**Comment by Machy8** [comment] 2023-02-28 22:53
I have forked your repository https://stackblitz.com/edit/github-a3hjjs?file=package.json,astro.config.mjs,server.mjs
- Added @astro/node and a few commands into the package.json

Could you please download it and test if something wasn't missing for example? If this example works? In your repo, there were no build/dev commands. 

Anyway, if it wont work on windows, I think, this `C:latihanastro-stylifysrcstylesstylify.css` will be the problem ...

**Comment by mzaini30** [comment] 2023-02-28 22:59
```bash
pnpm astro dev
pnpm astro build
```

**Comment by Machy8** [comment] 2023-02-28 23:21
This actually seems weird, like some bug with Windows and Node.js `path.join`... 

I will try to reproduce it on some of my Windows devices.

**Comment by mzaini30** [comment] 2023-02-28 23:24
I think the problem because I use Git Bash. In Windows Command Prompt or PowerShell, the path is using `\`. But, in Git Bash, the path is `/`

**Comment by Machy8** [comment] 2023-02-28 23:29
This should be solved automatically by `path.join()` by Node.js as it should use platform specific separators, that's why it is used for joining parts of paths. But in your case, it doesn't use any.

I have cloned your repo, it works fine on Linux and Mac. 

I will have to check it out on Windows.

**Comment by mzaini30** [comment] 2023-03-01 00:38
Yes, very difficult coding in Windows. I rewerite my packages after migration from Linux. Hehehehe..

**Comment by Machy8** [comment] 2023-03-02 16:05
Note for further readers: 
- You should not use path.join for joining wildcards `path.join(dir, '**', '*.txt')` => `dir\\**\\*.txt` => matches * as simple literal, because it is escaped by slash, and not as a wildcard...🤦‍♂️ => https://github.com/micromatch/micromatch#backslashes
- Node can import only normalized paths, not windows absolute paths

**Comment by Machy8** [comment] 2023-03-04 15:47
@mzaini30 Hi, this should be fixed in the https://github.com/stylify/packages/releases/tag/v0.5.28 latest release. Could you please let me know, if it works? 

Also, a configuration hot reload was added, so if you modify the config, the bundler should use the new configuration without the need of restarting Astro again.

**Comment by Machy8** [comment] 2023-03-13 18:20
@mzaini30 Could you please respond?

**Comment by mzaini30** [comment] 2023-03-13 21:11
Wait

**Comment by mzaini30** [comment] 2023-03-13 21:48
It works.... amazing

![gambar](https://user-images.githubusercontent.com/7939342/224839648-2eb02f4d-37af-4dac-86f4-a2b05fb5e6a9.png)

![gambar](https://user-images.githubusercontent.com/7939342/224839725-57bbd828-c748-4488-aeee-17050ec02215.png)

**Comment by mzaini30** [comment] 2023-03-13 23:26
Sorry for waiting long

**Comment by Machy8** [comment] 2023-03-14 10:31
Good, thanks! Closing. In case you find any other bug, please create a new issue :).

**Closed** 2023-03-14 10:31 UTC
Labels: 🐞 bug
